#!/bin/zsh

DIR=$(dirname "${0:a}")
SCRIPT=$(basename "$0")

# write timestamp + message to stdout, redirected to logfile when running  from LaunchDaemon
function log() {
	timestamp=$(date +%Y-%m-%dT%H:%M:%S%z)
	echo "$timestamp [SCRIPT] $1"
}


# Wait until Finder is running to ensure a console user is logged in
while ! pgrep -q Finder ; do
		log "Waiting until console user is logged in"
		sleep 10
done


loggedInUser=$(scutil <<< "show State:/Users/ConsoleUser" | awk '/Name :/ && ! /loginwindow/ { print $3 }')
dseditgroup -o edit -n /Local/Default -a $loggedInUser -t user _lpadmin
log "Added user [$loggedInUser] to _lpadmin group"
